cmake_minimum_required(VERSION 3.15)
project(zadaniaKCPP)

set(CMAKE_CXX_STANDARD 20)

add_executable(LStringStream LStringStream.cc)

add_executable(LManipulacjaStrumieniemCout LManipulacjaStrumieniemCout.cc)

add_executable(ZadCinCoutFile ZadCinCoutFile.cc)

add_executable(ZadCandCPP ZadCandCPP.cc)

add_executable(ZadTabelaFormat ZadTabelaFormat.cc)

add_executable(ZadTemperaturaFormat ZadTemperaturaFormat.cc)

add_executable(ZadDaneNaukoweFormat ZadDaneNaukoweFormat.cc)

add_executable(ZadParzysta ZadParzysta.cc)

add_executable(ZadParzystaCase ZadParzystaCase.cc)

add_executable(ZadPetle ZadPetle.cc)

add_executable(ZadSwitch ZadSwitch.cc)

add_executable(ZadForA ZadForA.cc)

add_executable(LSilnia LSilnia.cc)

add_executable(LKsztalt LKsztalt.cc)

add_executable(LWhileA LWhileA.cc)

add_executable(LGra LGra.cc)

add_executable(ZadStudent ZadStudent.cc)

add_executable(ZadPreprocesor ZadPreprocesor.cc)