cmake_minimum_required(VERSION 3.15
)
project(zadaniaKCPP)

set(CMAKE_CXX_STANDARD 20)


add_executable(ZadCharExample ZadCharExample.cc)

add_executable(ZadClassExample ZadClassExample.cc)

add_executable(ZadEnumExample ZadEnumExample.cc)

add_executable(ZadMainExample ZadMainExample.cc)

add_executable(ZadStringExample ZadStringExample.cc)

